EasyNote/Models/Note.cs
using EasyNote.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace EasyNote.Models
{
    public class Note
    {
        public int Id { get; set; }
        [Required]
        [MaxLength(100)]
        public string Title { get; set; }
        public string Content { get; set; }
        [Required]
        [ForeignKey("Author")]
        public string AuthorId { get; set; }
        public virtual ApplicationUser Author { get; set; }

        public NoteVM ToViewModel()
        {
            return new NoteVM()
            {
                Id = Id,
                Title = Title,
                Content = Content
            };
        }
    }
}

EasyNote/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EasyNote.Controllers
{
    //[Authorize]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

EasyNote/Controllers/NotesController.cs
using EasyNote.Models;
using EasyNote.Models.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace EasyNote.Controllers
{
    [Authorize]
    public class NotesController : BaseController
    {
        public ActionResult GetNotes()
        {
            string userId = User.Identity.GetUserId();
            List<NoteVM> notes = db.Notes.Where(x => x.AuthorId == userId).ToList().Select(x => x.ToViewModel()).ToList();
            return Json(notes, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult PostNote(PostNoteVM vm)
        {
            if (ModelState.IsValid)
            {
                Note note = new Note()
                {
                    Title = vm.Title,
                    Content = vm.Content,
                    AuthorId = User.Identity.GetUserId(),
                };
                db.Notes.Add(note);
                db.SaveChanges();
                return Json(note.ToViewModel());
            }
            Response.StatusCode = (int)HttpStatusCode.BadRequest;
            return Json(ModelState);
        }

        [HttpPost]
        public ActionResult UpdateNote(NoteVM vm)
        {
            if (ModelState.IsValid)
            {
                string userId = User.Identity.GetUserId();
                Note note = db.Notes.Find(vm.Id);
                if (note == null || note.AuthorId != userId)
                {
                    return HttpNotFound();
                }

                note.Title = vm.Title;
                note.Content = vm.Content;
                db.SaveChanges();
                return Json(note.ToViewModel());
            }
            Response.StatusCode = (int)HttpStatusCode.BadRequest;
            return Json(ModelState);
        }

        [HttpPost]
        public ActionResult DeleteNote(int id)
        {
            Note note = db.Notes.Find(id);
            if (note == null || note.AuthorId != User.Identity.GetUserId())
            {
                return HttpNotFound();
            }
            db.Notes.Remove(note);
            db.SaveChanges();
            return Json(note.ToViewModel());
        }
    }
}

EasyNote/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

EasyNote/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

EasyNote/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@if (!User.Identity.IsAuthenticated)
{
    <div class="jumbotron" style="margin-top:3rem">
        <h1>Easy Note</h1>
        <p class="lead">Wasy Note is an application where you can keep your note. <br />Please sign in to start using app.</p>
        <p><a href="@Url.Action("Login", "Account")" class="btn btn-primary btn-lg">Sign in &raquo;</a></p>
    </div>
}
else
{
    @Html.Partial("_Notes")
}

@section scripts {
    <script>
        var selectedLink = null;
        function listNotes() {
            $.ajax({
                type: "get",
                url: "@Url.Action("GetNotes","Notes")",
                success: function (data) {
                    for (var i = 0; i < data.length; i++) {
                        var note = data[i];
                        addNote(note);
                    }
                    SelectFirst();
                }
            });
        }

        function newNote() {
            $.ajax({
                type: "post",
                url: "@Url.Action("PostNote","Notes")",
                data: { Title : "New Note", Content:"" },
                success: function (data) {
                    addNote(data);
                    SelectFirst();
                    $("#title").select();
                }
            });
        }

        function addNote(note) {
            var a = $("<a/>")
                .attr("href", "#")
                .text(note.Title)
                .addClass("list-group-item");
            a[0].note = note;
            a.prependTo("#notes");
        }

        function SelectFirst() {
            let a = $("#notes > a")[0];
            select(a);
        }

        function select(a) {
            if (!a) {
                $("#frmNote").hide();
                selectedLink = null;
                return;
            }
            $("#frmNote").show();
            selectedLink = a;
            $("#notes > a").removeClass("active");
            $(a).addClass("active");
            $("#id").val(a.note.Id);
            $("#title").val(a.note.Title);
            $("#content").val(a.note.Content);
        }

        listNotes();

        $("#btnNew").click(function () {
            newNote();
        });

        $("#frmNote").submit(function (event) {
            event.preventDefault();
            if (!selectedLink) return;
            var formData = $(this).serialize();
             $.ajax({
                type: "post",
                url: "@Url.Action("UpdateNote","Notes")",
                data: formData,
                 success: function (data) {
                     selectedLink.note = data;
                     selectedLink.textContent = data.Title;
                }
            });

        });

        $("#btnDelete").click(function () {
            var selectedIndex = $(selectedLink).index();
            $.ajax({
                type: "post",
                url: "@Url.Action("DeleteNote","Notes")/" + selectedLink.note.Id,
                success: function (data) {
                    $(selectedLink).remove();
                    selectedLink = null;
                    select($("#notes > a")[selectedIndex] || $("#notes > a").last()[0]);
                }
            });
        });

        $("body").on("click", "#notes > a", function (event){
            event.preventDefault();
            select(this);
        });


    </script>
}

EasyNote/Views/Home/_Notes.cshtml
<div class="row notes-page">
    <div class="row">
        <div class="col-md-3">
            <div class="notes-heading-bar">
                <h2 class="notes-heading">Notes</h2>
                <button class="btn btn-success btn-sm" id="btnNew">
                    <i class="fas fa-plus"></i>
                </button>
            </div>
            <div class="list-group"  id="notes">
                @*<a href="#" class="list-group-item active">
                    Cras justo odio
                </a>
                <a href="#" class="list-group-item">Dapibus ac facilisis in</a>
                <a href="#" class="list-group-item">Morbi leo risus</a>
                <a href="#" class="list-group-item">Porta ac consectetur ac</a>
                <a href="#" class="list-group-item">Vestibulum at eros</a>*@
            </div>
        </div>
        <div class="col-md-9">
            <form id="frmNote" method="post" style="display:none">
                @Html.AntiForgeryToken()
                <input type="hidden" value="" id="id" name="id" />
                <div class="form-group">
                    <input id="title" name="title" type="text" class="form-control" placeholder="Title" required maxlength="100"/>
                </div>
                <div class="form-group">
                    <textarea id="content" name="content" class="form-control" placeholder="Your Note" rows="10"></textarea>
                </div>
                <div>
                    <button type="submit" id="btnSave" class="btn btn-primary">Save</button>
                    <button type="button" id="btnDelete" class="btn btn-danger">Delete</button>
                </div>
            </form>
        </div>
    </div>
</div>